version: "3.9"
services:
  fleet-api:
    image: fleet-api:v.1.0.0
    build:
      context: ./Fleet.Api
      tags:
        - fleet-api:v.1.0.0
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=test123.!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https/ # Windows-specific bind mount
          
  fleet-client:
    image: fleet-client:v.1.0.0
    build:
      context: ./Fleet.Client
      tags:
        - fleet-client:v.1.0.0
    ports:
      - "4200:80"
    depends_on:
      - fleet-api
    environment:
      - API_URL=https://localhost:8081/api
