version: '3.8'

services:
  fleet-api:
    image: fleet-api:1.0.0
    ports:
      - "5000:8080"
  fleet-client:
    image: fleet-client:1.0.0
    ports:
      - "4200:80"
    depends_on:
      - fleet-api
    environment:
      - API_URL=http://localhost:5000