name: Backend CI/CD

on:
  push:
    paths:
      - 'FleetManagement/Fleet.Api/**'
      - '.github/workflows/backend.yml'
    branches:
      - main
  pull_request:
    paths:
      - 'FleetManagement/Fleet.Api/**'
      - '.github/workflows/backend.yml'
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.100

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal --no-build
